### ISSUE TITLE
Refactor `query()` to use `read_with_timeout()`

### ISSUE THREAD

**Issue by stevenaleung** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#122]
In `Instrument.jl`, the `query()` function has logic that can be replaced with `read_with_timeout()`. After refactoring, `read_with_timeout()` might need a `throws_error` input to determine whether it throws an error when used with `query()` or exits silently when used with `clear_buffer()`

**Comment by mofii** [comment]
@stevenaleung can I get you to add a brief description of this?

**Comment by mofii** [comment]
This was fixed by #174
