### ISSUE TITLE
Feature request: arbitrary SCPI commands

### ISSUE THREAD

**Issue by quintinstedman** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#127]
Many lab instruments have hundreds of commands available, and it's not reasonable to expect TcpInstruments to have functionality covering all of them. It would be helpful if the user could send arbitrary SCPI commands to an instrument and read the responses to queries. This would allow more advanced users to use the more specialized capabilities of the instruments while keeping the package streamlined.

**Comment by mofii** [comment]
It's undocumented, but the internal function that sends the commands to the devices is `f_query()`
You could try:
```julia
TcpInstruments.f_query(instr, "<SCPI cmd string>"; timeout=3)
```

**Comment by mofii** [comment]
@quintinstedman see PR #130 that I expect will be included in the next release.
