### ISSUE TITLE
High resolution scope acquisition

### ISSUE THREAD

**Issue by quintinstedman** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#156]
Using averaging allows extra bits of vertical resolution in the oscilloscope (see p. 231 of the Keysight 4000 X-Series oscilloscope user's guide). The BYTE data transfer format currently used by this package only allows 8-bit access to the the waveform data (see p. 1399 of the programming manual). The least significant bits are discarded. It would be nice if a different data transfer format was used or available as an option that allows the maximum 12 bits of resolution to be retrieved.

**Comment by mofii** [comment]
Closed by #163
