### ISSUE TITLE
get_impedance bug

### ISSUE THREAD

**Issue by quintinstedman** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#224]
### Bug description
get_impedance isn't working. It seems to be an issue with Unitful. Downgrading Unitful to v1.11.0 solved the problem.

### Steps to reproduce the behavior along with the error stacktrace
```
using TcpInstruments
using Unitful
Z_analyzer= initialize(Agilent4294A, Z_analyzer_address);
Z_analyzer= initialize(Agilent4294A, Z_analyzer_address);
```

### Stacktrace
ERROR: UndefVarError: R not defined
Stacktrace:
 [1] get_impedance(ia::TcpInstruments.Instrument{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/H4lCH/src/impedance_analyzer/Agilent4294A.jl:89
 [2] top-level scope
   @ REPL[10]:1

### Versions
TcpInstruments.jl version/commit: 0.11.13
Julia version: 1.7.3

### Priority level (optional)
Not

**Comment by mofii** [comment]
Closed by #225
