### ISSUE TITLE
get_volt_ac not working for Agilent4294a

### ISSUE THREAD

**Issue by quintinstedman** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#37]
When I run this, I get the error message below. get_volt_dc works fine.

ERROR: MethodError: no method matching *(::SubString{String}, ::Unitful.FreeUnits{(V,), 𝐋² 𝐌 𝐈⁻¹ 𝐓⁻³, nothing})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  *(::Union{AbstractChar, AbstractString}, ::Union{AbstractChar, AbstractString}...) at strings/basic.jl:260
  *(::Union{Dates.Day, Dates.Hour, Dates.Microsecond, Dates.Millisecond, Dates.Minute, Dates.Nanosecond, Dates.Second, Dates.Week}, ::Unitful.Units) at /Users/admin/.julia/packages/Unitful/PcVKX/src/dates.jl:90
  ...
Stacktrace:
 [1] get_volt_ac(i::TcpInstruments.Instr{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/6H4Ex/src/impedance_analyzer/Agilent4294A.jl:57
 [2] top-level scope
   @ REPL[52]:1

**Comment by mofii** [comment]
Fixed in commit 89f74f377fec757121c5a98c74190fe8509c11fd
@JuliaRegistrator register branch=main

**Comment by mofii** [comment]
@JuliaRegistrator register
