### ISSUE TITLE
Impedance analyzer units

### ISSUE THREAD

**Issue by quintinstedman** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#57]
The impedance analyzer get_impedance function makes the units of everything ohms. But, data from the impedance analyzer is not always in ohms. It may be degrees.

**Comment by stevenaleung** [comment]
Thoughts on making `get_impedance()` output R-X (resistance-reactance) data by default? Degrees can be easily calculated with `angle.(data)`

**Comment by quintinstedman** [comment]
That's fine with me as long as the display on the impedance analyzer can still show magnitude and phase. Magnitude and phase is often more useful to view.

**Comment by stevenaleung** [comment]
In PR #73, `get_impedance()` switches the impedance analyzer window to complex mode during data transfer then switches back to magnitude & phase mode. We can explore this further to see what works best for you
