### ISSUE TITLE
Complex impedance analyzer data?

### ISSUE THREAD

**Issue by quintinstedman** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#59]
The impedance analyzer data is complex by default, and there is not documentation showing how to make it real. In the typical use case, the data is real.

**Comment by stevenaleung** [comment]
@quintinstedman Is this still an existing issue?

Does `real.(ustrip.(data))` solve the problem?

**Comment by quintinstedman** [comment]
That does solve the problem. However, if the data is always real (we are not returning impedance as a complex number), we should still update the code to return real numbers instead to simplify things.

**Comment by stevenaleung** [comment]
We could have several different functions that each return only one type of measurement. For example, `get_impedance()`, `get_impedance_phase()`, `get_resistance()`, etc. I think this will make it easier to use and debug

Which of the following measurements will be useful?
<img src="https://user-images.githubusercontent.com/4917419/140836411-7432e8f8-b6c1-4864-837d-82fc8e31eec7.png" width=70%>

**Comment by quintinstedman** [comment]
Impedance + phase, real + imaginary, etc. are all mathematically equivalent. I prefer to stick to one so that my data is always in the same format and I avoid confusion. I can then easily calculate the others as needed. I would always just use get_impedance_phase, or get_impedance (if that returns the full complex valued impedance)

I would not use a function like get_resistance that leaves out part of the impedance data.

**Comment by stevenaleung** [comment]
Sounds good - let's stick with `get_impedance()` returning full complex valued impedance for now then
