### ISSUE TITLE
No get_frequency_range function

### ISSUE THREAD

**Issue by quintinstedman** [Orchard-Ultrasound-Innovation/TcpInstruments.jl#62]
It is listed in the code as an available function, but not implemented. This would be quite a useful function to have. We can get by without it for a while by creating the array manually for each measurement, but it creates extra work for the user.

**Comment by mofii** [comment]
@quintinstedman this is for the impedance analyzer?
Where is the command listed?

**Comment by quintinstedman** [comment]
I see it if I look in the actual code.

**Comment by stevenaleung** [comment]
A `get_frequency_limits()` function is exported by TcpInstruments.jl (it's implemented in impedance_analyzer/all.jl)
